# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_DB: saq_db
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: testing
    expose:
    - "5432" # Publishes 5432 to other containers but NOT to host machine
    ports:
    - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
